### ISSUE TITLE
remove `beautify` option (`js-beautify` package too)

### ISSUE THREAD

**Issue by evilebottnawi** [commenthol/serialize-to-js#10]
Why:
- reduce package size
- no need beautify by default, main purpose is serialization, not pretty printing 
- there a lot of other buitifiers (example i like prettier)

**Comment by commenthol** [comment]
you can use the serialization without beautifier. 
```js
const serialize = require('serialize-to-js/lib/serialize')
```
does the trick.

**Comment by evilebottnawi** [comment]
@commenthol we want this library in big packages like loader/plugins for webpack, and it is increase size our packages, we don't want to do fork because of this problem, it is really looks weird

**Comment by evilebottnawi** [comment]
Can we reconsider this issue, otherwise we really have to do fork?

**Comment by commenthol** [comment]
Hi @evilebottnawi,
there is PR #12 to split things up as you requested. Would be nice if you could have a look at it if that fits your/ and maybe others needs.
