### ISSUE TITLE
SyntaxError: Unexpected token {

### ISSUE THREAD

**Issue by evilebottnawi** [commenthol/serialize-to-js#9]
Code:
```js
const lib = require('serialize-to-js');

const testData = {
  mtd(arg) { return arg },
};

const serializedData = lib.serialize(testData);
const deserializeData = lib.deserialize(serializedData, true);

console.log(testData);
console.log(deserializeData);
```

We want to migrate from `serialize-javascript` (https://github.com/yahoo/serialize-javascript) in webpack to your library. Two blokers:
- This issue
- https://github.com/commenthol/serialize-to-js/issues/7

**Comment by commenthol** [comment]
Please note that deserialize method gets removed in #8.

**Comment by evilebottnawi** [comment]
@commenthol i know, custom eval/Function also failed
